version: "3.8"
services:
  api-service:
    container_name: api-container
    build:
      context: ./1
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
networks:
  backend_network:
    driver: bridge
    driver_opts:
      parent: en0
